package com.jets.dao;
// Generated Mar 4, 2018 5:20:16 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private String productPrice;
     private String producctDescription;
     private Integer productQuantity;
     private byte[] productImage;

    public Product() {
    }

	
    public Product(String productName, String productPrice, String producctDescription, byte[] productImage) {
        this.productName = productName;
        this.productPrice = productPrice;
        this.producctDescription = producctDescription;
        this.productImage = productImage;
    }
    public Product(String productName, String productPrice, String producctDescription, Integer productQuantity, byte[] productImage) {
       this.productName = productName;
       this.productPrice = productPrice;
       this.producctDescription = producctDescription;
       this.productQuantity = productQuantity;
       this.productImage = productImage;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(String productPrice) {
        this.productPrice = productPrice;
    }
    public String getProducctDescription() {
        return this.producctDescription;
    }
    
    public void setProducctDescription(String producctDescription) {
        this.producctDescription = producctDescription;
    }
    public Integer getProductQuantity() {
        return this.productQuantity;
    }
    
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }
    public byte[] getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(byte[] productImage) {
        this.productImage = productImage;
    }




}


