package com.jets.dao;
// Generated Mar 4, 2018 5:20:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private Date userBirthday;
     private String userPassword;
     private String userJob;
     private String userEmail;
     private String userCreditLimt;
     private String address;

    public User() {
    }

	
    public User(String userName, Date userBirthday, String userPassword, String userEmail, String address) {
        this.userName = userName;
        this.userBirthday = userBirthday;
        this.userPassword = userPassword;
        this.userEmail = userEmail;
        this.address = address;
    }
    public User(String userName, Date userBirthday, String userPassword, String userJob, String userEmail, String userCreditLimt, String address) {
       this.userName = userName;
       this.userBirthday = userBirthday;
       this.userPassword = userPassword;
       this.userJob = userJob;
       this.userEmail = userEmail;
       this.userCreditLimt = userCreditLimt;
       this.address = address;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Date getUserBirthday() {
        return this.userBirthday;
    }
    
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserJob() {
        return this.userJob;
    }
    
    public void setUserJob(String userJob) {
        this.userJob = userJob;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserCreditLimt() {
        return this.userCreditLimt;
    }
    
    public void setUserCreditLimt(String userCreditLimt) {
        this.userCreditLimt = userCreditLimt;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


