package com.jets.dao;
// Generated Mar 18, 2018 7:53:02 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String userBirthday;
     private String userPassword;
     private String userJob;
     private String userEmail;
     private Double userCreditLimt;
     private String address;
     private String gender;
     private String type;

    public User() {
    }

	
    public User(String userName, String userPassword, String userEmail, String address, String gender, String type) {
        this.userName = userName;
        this.userPassword = userPassword;
        this.userEmail = userEmail;
        this.address = address;
        this.gender = gender;
        this.type = type;
    }
    public User(String userName, String userBirthday, String userPassword, String userJob, String userEmail, Double userCreditLimt, String address, String gender, String type) {
       this.userName = userName;
       this.userBirthday = userBirthday;
       this.userPassword = userPassword;
       this.userJob = userJob;
       this.userEmail = userEmail;
       this.userCreditLimt = userCreditLimt;
       this.address = address;
       this.gender = gender;
       this.type = type;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserBirthday() {
        return this.userBirthday;
    }
    
    public void setUserBirthday(String userBirthday) {
        this.userBirthday = userBirthday;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserJob() {
        return this.userJob;
    }
    
    public void setUserJob(String userJob) {
        this.userJob = userJob;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Double getUserCreditLimt() {
        return this.userCreditLimt;
    }
    
    public void setUserCreditLimt(Double userCreditLimt) {
        this.userCreditLimt = userCreditLimt;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


